# Nestory SwiftLint Configuration
# Enforces architecture and code quality standards

# Reporter configuration for CI-friendly output
reporter: github-actions-logging
strict: false

excluded:
  - .build
  - build
  - DerivedData
  - Pods
  - Carthage
  - DevTools/nestoryctl/.build
  - Sources/NestoryGuards/.build
  - "**/.build"
  - "**/DerivedData"
  - .swiftpm
  - Package.resolved
  - "*.xcodeproj"
  - "*.xcworkspace"
  - fastlane
  - vendor
  - Tests  # Exclude Tests to focus on app sources

included:
  - App-Main
  - App-Widgets
  - Features
  - UI
  - Services
  - Infrastructure
  - Foundation

opt_in_rules:
  # Code Quality
  - empty_count
  - empty_string
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_optional_boolean
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_imports
  - switch_case_on_newline
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
  
  # Documentation (disabled for now - too noisy)
  # - missing_docs
  
  # Performance
  - array_init
  - empty_collection_literal
  - enum_case_associated_values_count
  - flatmap_over_map_reduce
  - reduce_into
  
  # SwiftUI specific
  - accessibility_label_for_image
  - accessibility_trait_for_button

disabled_rules:
  - trailing_whitespace  # Let formatter handle this
  - orphaned_doc_comment
  - trailing_comma  # Don't enforce trailing commas

# Custom Rules
custom_rules:
  layer_header_required:
    included: ".*\\.swift"
    name: "Layer Header Required"
    regex: '(^//\\s+Layer:\\s+.+\\n//\\s+Module:\\s+.+)'
    match_kinds: comment
    message: "Missing required layer header."
    severity: warning
    
  todo_must_reference_adr:
    name: "TODO Must Reference ADR"
    regex: '(//\s*(TODO|FIXME)(?!.*ADR-\d{4}))'
    message: "TODOs and FIXMEs must reference an ADR (e.g., // TODO: ADR-0001)"
    severity: warning  # Changed from error to warning for now

  no_print_statements:
    name: "No Print Statements"
    regex: '^\s*print\('
    message: "Use logger or NSLog instead of print statements"
    severity: warning
    
  no_force_cast_in_production:
    name: "No Force Cast in Production"
    regex: 'as!\s'
    message: "Avoid force casting - use conditional casting instead"
    severity: error

# Length Rules (reasonable limits)
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

function_parameter_count:
  warning: 6
  error: 10

# Naming
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 45
    error: 60
  excluded:
    - id
    - ok
    - no
    - to
    - up
    - on
    - at
    - by
    - x
    - y
    - z
    - w
    - i
    - j
    - k
    - n
    - m
    - dx
    - dy
    - pi
    - e
    - ID
    - URL
    - URI

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 70
  excluded:
    - ID
    - URL
    - URI

# Metrics (realistic for SwiftUI apps)
cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

nesting:
  type_level: 3  # Increased for SwiftUI
  function_level: 4  # Increased for SwiftUI modifiers

# Force Unwrapping (warnings not errors for pragmatic development)
force_cast: warning
force_try: warning
force_unwrapping:
  severity: warning

# Imports
sorted_imports: 
  severity: warning

# SwiftUI Specific
multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

trailing_closure:
  only_single_muted_parameter: true

# Note: Reporter already configured at top of file