name: Nestory
options:
  bundleIdPrefix: com.nestory
  deploymentTarget:
    iOS: 17.0
  developmentLanguage: en
  xcodeVersion: 15.0
  createIntermediateGroups: true
  generateEmptyDirectories: true

attributes:
  ORGANIZATIONNAME: Nestory
  DEVELOPMENT_TEAM: 2VXBQV4XC9

configs:
  Debug:
    xcconfig: Config/Debug.xcconfig
  Release:
    xcconfig: Config/Release.xcconfig

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    SWIFT_VERSION: 6.0
    DEVELOPMENT_TEAM: 2VXBQV4XC9
    CODE_SIGN_STYLE: Automatic
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0

targets:
  Nestory:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    
    sources:
      - path: App-Main
        excludes:
          - "RootFeature.swift"
          - "RootView.swift"
          - "SearchView-Old.swift"
      - path: Foundation/Models
      - path: Foundation/Core
      - path: Foundation/Utils
      - path: Infrastructure/Storage
      - path: Infrastructure/Security
      - path: Services
      - path: UI/UI-Core
      - path: UI/UI-Components
      - path: Config/FeatureFlags.swift
      
    resources:
      - path: App-Main/Assets.xcassets
        
    settings:
      base:
        PRODUCT_NAME: Nestory
        PRODUCT_BUNDLE_IDENTIFIER: com.nestory.app.dev
        INFOPLIST_FILE: App-Main/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        
    dependencies:
      - sdk: SwiftData.framework
      - sdk: CloudKit.framework

schemes:
  Nestory-Dev:
    build:
      targets:
        Nestory: all
    run:
      config: Debug
      environmentVariables:
        CLOUDKIT_CONTAINER: iCloud.com.nestory.app.dev
    test:
      config: Debug
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Debug
