# Prometheus configuration for iOS telemetry pipeline
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files: []

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  # Scrape Pushgateway (for legacy CI metrics)
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
    honor_labels: true

# Remote write is handled by OpenTelemetry Collector
# iOS metrics come via OTLP -> Collector -> Remote Write to Prometheus