name: Continuous Integration

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  SWIFT_VERSION: '5.9'

jobs:
  ci-verification:
    name: CI Verification
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'
      
      - name: Cache Swift Package Manager
        uses: actions/cache@v3
        with:
          path: |
            .build
            ~/Library/Developer/Xcode/DerivedData
            DevTools/nestoryctl/.build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      
      - name: Install Tools
        run: |
          if ! command -v swiftformat &> /dev/null; then
            echo "📦 Installing SwiftFormat..."
            brew install swiftformat
          fi
          if ! command -v swiftlint &> /dev/null; then
            echo "📦 Installing SwiftLint..."
            brew install swiftlint
          fi
      
      - name: Build Project
        run: |
          echo "🔨 Building project..."
          swift build
      
      - name: Build nestoryctl
        run: |
          echo "🔨 Building nestoryctl..."
          swift build -c release --package-path DevTools/nestoryctl
      
      - name: Run Full Test Suite
        run: |
          echo "🧪 Running all tests..."
          swift test
      
      - name: SPEC Verification
        run: |
          echo "📋 Verifying SPEC integrity..."
          ./DevTools/nestoryctl/.build/release/nestoryctl spec-verify
      
      - name: Architecture Verification
        run: |
          echo "🏗️ Verifying architecture conformance..."
          ./DevTools/nestoryctl/.build/release/nestoryctl arch-verify
      
      - name: SPM Audit
        run: |
          echo "📦 Auditing SPM dependencies..."
          ./DevTools/nestoryctl/.build/release/nestoryctl spm-audit || echo "⚠️ Package.resolved not found (expected for initial setup)"
      
      - name: Full Guard Suite
        run: |
          echo "🔍 Running complete guard suite..."
          make guard
      
      - name: Generate Coverage Report
        run: |
          echo "📊 Generating coverage report..."
          swift test --enable-code-coverage || true
          echo "Coverage generation complete (if available)"
      
      - name: Update Build Status
        if: always()
        run: |
          echo "" >> BUILD_STATUS.md
          echo "## Main Branch CI: $(date '+%Y-%m-%d %H:%M:%S')" >> BUILD_STATUS.md
          echo "- Commit: ${{ github.sha }}" >> BUILD_STATUS.md
          echo "- Author: ${{ github.actor }}" >> BUILD_STATUS.md
          echo "- Status: ${{ job.status }}" >> BUILD_STATUS.md
          echo "- Guards: " >> BUILD_STATUS.md
          if [ "${{ job.status }}" == "success" ]; then
            echo "  ✅ All checks passed" >> BUILD_STATUS.md
          else
            echo "  ❌ Some checks failed" >> BUILD_STATUS.md
          fi
          echo "" >> BUILD_STATUS.md
      
      - name: Upload Build Status
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-status-main
          path: BUILD_STATUS.md
      
      - name: Upload Coverage
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            .build/*/codecov
            *.xcresult
      
      - name: Create Release Tag (if applicable)
        if: success() && contains(github.event.head_commit.message, '[release]')
        run: |
          VERSION=$(date +%Y.%m.%d-%H%M)
          git tag -a "guards-v${VERSION}" -m "Guard rails release ${VERSION}"
          git push origin "guards-v${VERSION}"